"""phase1 canonical schema

Revision ID: 94be8eadb99f
Revises: 
Create Date: 2026-09-06 17:16:13.883337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94be8eadb99f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_leases',
    sa.Column('agent_run_id', sa.String(length=40), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('agent_run_id')
    )
    op.create_table('agent_personalities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=60), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('verbosity', sa.Integer(), nullable=False),
    sa.Column('reasoning_style', sa.String(length=20), nullable=False),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('learned_from_feedback_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_personalities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_personalities_agent_id'), ['agent_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('agent_run_id', sa.String(length=40), nullable=True),
    sa.Column('requested_action', sa.Text(), nullable=False),
    sa.Column('risk', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('requester', sa.String(length=60), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('decided_by', sa.String(length=60), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_task_id'), ['task_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_task_id'), ['task_id'], unique=False)

    op.create_table('behavior_recordings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('agent_run_id', sa.String(length=40), nullable=True),
    sa.Column('recording_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recording_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('action_log_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavior_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_recordings_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_recordings_session_id'), ['session_id'], unique=False)

    op.create_table('cost_budget',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('limit_usd', sa.Float(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('agent_run_id', sa.String(length=40), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=12), nullable=False),
    sa.Column('sensitivity', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('sequence', name='uq_events_sequence')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_events_session_sequence', ['session_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('feedback_log',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=60), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_log_agent_id'), ['agent_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('result_ref', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('insights',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('insight_type', sa.String(length=24), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('key_findings_json', sa.JSON(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_calls',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('agent_run_id', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tokens_cached', sa.Integer(), nullable=True),
    sa.Column('usage_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_calls_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_calls_task_id'), ['task_id'], unique=False)

    op.create_table('qa_reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('code_file', sa.Text(), nullable=True),
    sa.Column('tests_generated', sa.Integer(), nullable=False),
    sa.Column('tests_executed', sa.Integer(), nullable=False),
    sa.Column('tests_passed', sa.Integer(), nullable=False),
    sa.Column('tests_failed', sa.Integer(), nullable=False),
    sa.Column('tests_skipped', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('diagnostics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_reports_task_id'), ['task_id'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('task_dag_json', sa.JSON(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('executions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('schedule_json', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_batches',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('batch_type', sa.String(length=40), nullable=False),
    sa.Column('task_ids_json', sa.JSON(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speedup_factor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_run_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.String(length=12), nullable=False),
    sa.Column('approval_id', sa.String(length=40), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_task_id'), ['task_id'], unique=False)

    op.create_table('workspace_templates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_workspace_id', sa.String(length=40), nullable=True),
    sa.Column('snapshot_path', sa.Text(), nullable=False),
    sa.Column('git_history_json', sa.JSON(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('container_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=40), nullable=True),
    sa.Column('cloned_from_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('depends_on_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('agent_type', sa.String(length=40), nullable=True),
    sa.Column('batch_id', sa.String(length=40), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_tasks_idempotency_key')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_state'), ['state'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('agent_type', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_state'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_state'))
        batch_op.drop_index(batch_op.f('ix_tasks_session_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_tasks_batch_id'))

    op.drop_table('tasks')
    op.drop_table('workspaces')
    op.drop_table('workspace_templates')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_task_id'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_agent_run_id'))

    op.drop_table('tool_calls')
    op.drop_table('task_batches')
    op.drop_table('sessions')
    op.drop_table('scheduled_jobs')
    op.drop_table('recipes')
    with op.batch_alter_table('qa_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_reports_task_id'))

    op.drop_table('qa_reports')
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_calls_task_id'))
        batch_op.drop_index(batch_op.f('ix_model_calls_agent_run_id'))

    op.drop_table('model_calls')
    op.drop_table('insights')
    op.drop_table('idempotency_keys')
    with op.batch_alter_table('feedback_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_log_agent_id'))

    op.drop_table('feedback_log')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_task_id'))
        batch_op.drop_index('ix_events_session_sequence')
        batch_op.drop_index(batch_op.f('ix_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_events_agent_run_id'))

    op.drop_table('events')
    op.drop_table('cost_budget')
    with op.batch_alter_table('behavior_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_recordings_session_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_recordings_agent_run_id'))

    op.drop_table('behavior_recordings')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_task_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_task_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_decision'))
        batch_op.drop_index(batch_op.f('ix_approvals_agent_run_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('agent_personalities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_personalities_agent_id'))

    op.drop_table('agent_personalities')
    op.drop_table('agent_leases')
    # ### end Alembic commands ###
